local AddOn = select(2, ...)

if AddOn.IsClassic then
    AddOn:AddStatPriority("DRUID")
        :SetPriority("Caster", "Hit 16% > Crit > SpDam > Int > Spirit > Stam")
        :SetPriority("Melee",  "Hit 9% > Agil > Str > Crit > AttPwr > Int > Stam > Spirit")
        :SetPriority("Tank",   "Armour > Stam > Def > Agil = Dodge > Hit 9% > Str > AttPwr > Crit")
        :SetPriority("Healer", "HealPwr > Mana > Int > Spirit > SpCrit > Stam")

    AddOn:AddStatPriority("HUNTER")
        :SetDefaultPriority("Hit 9% > Crit > Agil > AttPwr > Stam > Int > Spirit")

    AddOn:AddStatPriority("MAGE")
        :SetDefaultPriority("SpHit > SpCrit > SpDam > Int > Stam > Resist > Mana > Spirit")

    AddOn:AddStatPriority("PALADIN")
        :SetPriority("Holy",    "HealPwr > Int > Crit > Mana > Stam > Spirit")
        :SetPriority("Protect", "Stam > Def > Str > Agil > Armour > Int > Hit > SpPwr > Str > Int")
        :SetPriority("Retadin", "Hit 9% > Str > Agil = Crit > Att > SpPwr > Stam > Int")

    AddOn:AddStatPriority("PRIEST")
        :SetPriority("Shadow", "Hit 6% > SpDam = ShadowDam > Mana > Int > SpCrit > Spirit > Stam")
        :SetPriority("Healer", "HealPwr > Mana > Spirit > Int > SpCrit > Stam")

    AddOn:AddStatPriority("ROGUE")
        :SetDefaultPriority("Hit 9% > Agil > Str = Att > Crit")

    AddOn:AddStatPriority("SHAMAN")
        :SetPriority("Elemental",   "SpHit 16% > SpDam > SpCrit > Mana > Int > SpPen > Stam > Resist > Spirit")
        :SetPriority("Enhancement", "Weapon > Hit 6% > Crit > Str = Att > Agil > Mana > Int > Stam")
        :SetPriority("Healer",      "Mana > Int > Heal > SpCrit > Spirit > Stam > Resist > SpHit")

    AddOn:AddStatPriority("WARLOCK")
        :SetDefaultPriority("SpPwr > SpCrit > Hit 16% > SpPen > Int > Stam > Spirit")

    AddOn:AddStatPriority("WARRIOR")
        :SetPriority("DPS", "Weapon > Hit 6% > Crit > Str = Att > Agil > Stam > Armour > Parry > Def")
        :SetPriority("Tank", "Stam > Armour > Parry > Def > Agil > Str > Block > Weapon > Hit 6% > Crit")

elseif AddOn.IsBCC then
    AddOn:AddStatPriority("DRUID")
        :SetPriority("Caster",    "SpHit 16% (3% PVP) > SpDam > SpHaste > SpCrit > Int > Spirit > Mana > Stam > SpPen")
        :SetPriority("Melee",  "Agil > Hit 9% (5% PVP)> Expert 6.5% > Str > Crit > Haste > AttPwr > ArmPen > Stam = Int = Spirit = Mana")
        :SetPriority("Tank", "Expert 6.5% > Agil > Stam > Hit 9% (5% PVP) > Str > Crit > Dodge > Def > AttPwr > Resil > Armour > ArmPen")
        :SetPriority("Healer", "SpHeal > Spirit > Mana > Int > SpHaste > SpCrit > Stam")

    AddOn:AddStatPriority("HUNTER")
        :SetPriority("BeastMaster",     "Hit 9% > ArmPen > Agil > AttPwr > Crit")
        :SetPriority("Marksman",        "Hit 9% > ArmPen > Agil > AttPwr > Crit")
        :SetPriority("Charge Marksman", "Hit 9% > ArmPen > Agil > Crit > AttPwr")
        :SetPriority("Survivalist",     "Agil > Crit > Hit 6% (2% Raid) > ArmPen > AttPwr")

    AddOn:AddStatPriority("MAGE")
        :SetPriority("Arcane",     "SpDam = SpHeal > Int > SpCrit > SpHaste > SpHit 6% > Spirit > Mana")
        :SetPriority("Fire/Frost", "SpDam > SpCrit > SpHaste > SPHit 13% > Spirit > Mana > Int")

    AddOn:AddStatPriority("PALADIN")
        :SetPriority("Holy Damage",  "SpDam > Bonus Heal > SpHit > Stam > Str > AttPwr > Haste")
        :SetPriority("Holy Healer",   "HealPwr > Mana > SpCrit > Int > SpHaste")
        :SetPriority("Protect",      "Hit 9% > Str > SpDam > Stam > AttPwr > Haste > Agil = Crit")
        :SetPriority("Protect Tank", "Def 490 > Avoid 102.4% (Block > Dodge > Parry) > Stam > SpDam > Hit > Expert")
        :SetPriority("Retribution",  "Hit 9% > Expert > Str > AttPwr > Stam > Haste > ArmPen > Agil = Crit")

    AddOn:AddStatPriority("PRIEST")
        :SetDefaultPriority("Int > Bonus Heal > Spirit > Mana > Stam")
        :SetPriority("Healer",       "SPHaste > Bonus Heal > SpCrit > Spirit > Int > Mana > Stam")
        :SetPriority("Shadow",       "SpHit > SpDam > SPHaste > SpCrit > Int > Spirit > Mana > Stam")

    AddOn:AddStatPriority("ROGUE")
        :SetDefaultPriority("Expert > Hit > Agil > Crit > AttPwr > Str > Stam")

    AddOn:AddStatPriority("SHAMAN")
        :SetPriority("Elemental", "SpHit 16% (3% PVP) > SPDam > SpCrit > SpHaste > Int > Stam > SpPen > Mana > Spirit")
        :SetPriority("Enhance",   "Hit 9% (5% PVP > Expert 6.25% > Str = AttPwr > Crit > Agil > Hit 9%+ > Haste > ArmPen > Int > Stam > Mana > Spirit")
        :SetPriority("Healer",    "SpHeal > Mana > Int > SpHaste > SpCrit > Stam > Spirit")

    AddOn:AddStatPriority("WARLOCK")
      :SetDefaultPriority("SPDam > Stam > SpHit > SpCrit > Int > Spirit")

    AddOn:AddStatPriority("WARRIOR")
        :SetPriority("Arms",               "Hit > Expert > Crit > Str = AttPwr > Agil > Haste")
        :SetPriority("Fury",               "Hit > Expert > Str = AttPwr > Crit > Agil > Haste")
        :SetPriority("Protect Survival",   "Stam > Armor > Resist > Def > Dodge > Agil > Parry > Block > Resil")		
        :SetPriority("Protect Damage",     "Expert > Hit 9% > Weapon > Haste > Agil > Crit > Str = AttPwr")

elseif AddOn.IsWotLK then
    AddOn:AddStatPriority("DEATHKNIGHT")
        :SetPriority("Blood",    "Def 540 > Hit T-Cap > Stam > Expert > Dodge")
        :SetPriority("Frost",    "Hit Cap = Expert Cap > Str > ArmPen > Crit > Haste")
        :SetPriority("Unholy",   "Hit Cap > Str > Haste >ArmPen > Crit > Expert")
		
    AddOn:AddStatPriority("DRUID")
        :SetPriority("Balance",      "17% hit > SpPwr > Haste > Crit > Int > Spirit > Mana")
        :SetPriority("Feral Melee",  "Str > 8% Hit > Agil > 26 Expert > Crit > ArmPen > Haste > Feral AttPwr > AttPwr")
        :SetPriority("Feral Tank",   "Stam > 26 Expert > Agi > 8% Hit > Expert+ > Armour > Str > Haste > ArmPen > Def > Crit > Dodge > AttPwr > Armour+")
        :SetPriority("Restoration",  "SpPow > Haste > Mana > Int > Spirit > Crit")

    AddOn:AddStatPriority("HUNTER")
        :SetPriority("BeastMaster",     "Hit Cap > AttPow > Agil > Crit > ArmPen > Haste")
        :SetPriority("Marksman",        "Hit Cap > Agi > ArmPen > Crit > AttPwr > Haste")
        :SetPriority("Survivalist",     "Hit Cap > Agil > Crit > AttPwr > ArmPen > Haste")

    AddOn:AddStatPriority("MAGE")
        :SetPriority("Arcane",     "SpHit Cap > SpPow = Haste > Crit > Spirit > Int > Stam > Mana")
        :SetPriority("Fire",       "Hit Cap > SpPow > Crit > Haste > Spirit > Int > Stam > Mana")
        :SetPriority("Frost",      "SpHit Cap > SpPow = Haste > Crit > Spirit > Int > Stam > Mana")
		
    AddOn:AddStatPriority("PALADIN")
        :SetPriority("Holy",         "Int > SpHaste > Mana > SpCrit")
        :SetPriority("Protect",      "Def 540 > Stam > Block > Expert > Hit > Dodge > Parry")
        :SetPriority("Retribution",  "Hit Cap > Expert > Str > Agi > AttPwr > Crit > Haste > ArmPen")

    AddOn:AddStatPriority("PRIEST")
        :SetPriority("Disipline",       "Haste S-Cap > SpPow > Crit >  Haste S-Cap+ > Int > Spirit > Mana")
        :SetPriority("Holy",       "Haste > Int > SpPow > Spirit > Crit > Mana")
        :SetPriority("Shadow",       "Hit > SpPwr > Haste > Crit > Spirit")

    AddOn:AddStatPriority("ROGUE")
        :SetPriority("Assassin", "Hit Cap > Expert > Agil > Str = AttPow > Haste > Crit > ArmPen")
        :SetPriority("Combat",   "Hit Cap > Expert > Agil > Str = AttPow > ArmPen > Haste > Crit")
		:SetPriority("Stealth",  "Hit Cap > Expert > Agil > Str = AttPow > ArmPen > Haste > Crit")
				
    AddOn:AddStatPriority("SHAMAN")
        :SetPriority("Elemental", "17% Hit > SpPow > Haste > Crit > Int > Mana")
        :SetPriority("Enhance",   "17% Hit > 26 Expert > AttPwr > Haste > Agil > Int > SpPwr > Crit > Str > ArmPen")
        :SetPriority("Restro",    "SpPow > Haste > Mana > Crit > Int")

    AddOn:AddStatPriority("WARLOCK")
        :SetPriority("Affliction",          "Hit Cap > SpPow > Haste > Crit > Spirit > Int")	
        :SetPriority("DPS Demonology", 		"Hit Cap > SpPow > Haste > Crit > Int")	
		:SetPriority("Support Demonology",  "Hit Cap > SpPow > Spirit > Crit > Int")	
		:SetPriority("Destruction",         "Hit Cap > SpPow > Haste > Crit > Spirit > Int")

    AddOn:AddStatPriority("WARRIOR")
        :SetPriority("Arms",      "Hit > ArmPen > Str > Crit > Expert > Haste")
        :SetPriority("Fury",      "Hit > Expert > ArmPen > Str > Crit > Haste")
        :SetPriority("Protect",   "Def > Stam > Hit > Expert > Armour > Block > Dodge > Parry")		

elseif AddOn.IsCata then
    AddOn:AddStatPriority("DEATHKNIGHT")
        :SetPriority("Blood",    "Stam > Mast > Dodge > Parry > 8% > Expert")
        :SetPriority("Frost",    "Str > 8% Hit > Expert > Haste > Mast > Crit")
        :SetPriority("Unholy",   "Str > 8% Hit > Haste > Crit > Mast > Expert")
		
    AddOn:AddStatPriority("DRUID")
        :SetPriority("Balance",      "Int > SpPow > Spirit = Hit > Haste > Mast > Crit")
        :SetPriority("Feral Melee",  "Agil > Mast > Hit > Expert > Crit > Haste")
        :SetPriority("Feral Tank",   "Agil > Expert >Hit > Crit > Haste > Stam > Mast")
        :SetPriority("Restoration",  "Int > SpPow > Haste 22% > Mast > Crit > Spirit > Stam")

    AddOn:AddStatPriority("HUNTER")
        :SetPriority("BeastMaster",     "Agil > 8% Hit > Crit > Mast > Haste")
        :SetPriority("Marksman",        "Agil > 8% Hit > Crit > Haste > Mast")
        :SetPriority("Survivalist",     "Agil > 8% Hit > Crit > Mast > Haste")

    AddOn:AddStatPriority("MAGE")
        :SetPriority("Arcane",     "Int > Hit > Haste S-Cap > Mastery > Haste > Crit")
        :SetPriority("Fire",       "Int > Hit > Crit > Haste > Mast")
        :SetPriority("Frost",      "Int > Hit > Crit 33% > Haste > Mast > Crit 33%+")
		
    AddOn:AddStatPriority("PALADIN")
        :SetPriority("Holy",         "Int > SpPow > Haste > Spirit > Crit > Mast")
        :SetPriority("Protect",      "Stam > Mast > Hit > Expert > Dodge = Parry > Crit")
        :SetPriority("Retribution",  "Str > Mast > 8% Hit > Expert > Crit > Haste")

    AddOn:AddStatPriority("PRIEST")
        :SetPriority("Disipline",       "Int > Spirit > Haste > Mast > Crit")
        :SetPriority("Holy",       "Int > Spirit > Haste > Mast > Crit")
        :SetPriority("Shadow",       "Int > 17% Hit > Haste > Mast > Crit")

    AddOn:AddStatPriority("ROGUE")
        :SetPriority("Assassin", "Agil > 17% Hit > Mast > Haste > Expert > Crit > Stam")
        :SetPriority("Combat",   "Agil > 8% Hit > Expert > Haste > Mast > Crit > Stam")
		:SetPriority("Stealth",  "Agil > 8% Hit > Expert > Haste > Crit > Mast")
				
    AddOn:AddStatPriority("SHAMAN")
        :SetPriority("Elemental", "Int > SpPow > Spirit = Hit > Haste > Mast > Crit")
        :SetPriority("Enhance",   "Agil > Hit > Expert > Mast > Crit > Haste")
        :SetPriority("Restro",    "Int > SpPow > Haste > Crit > Mast > Spirit")

    AddOn:AddStatPriority("WARLOCK")
        :SetPriority("Affliction",          "Int > 17% Hit > Haste > Crit > Mast")	
        :SetPriority("Demonology", 		"Int > 17% Hit > Haste 21% > Mast > Crit")		
		:SetPriority("Destruction",         "Int > 17% Hit > Haste 30% > Crit > Mast")

    AddOn:AddStatPriority("WARRIOR")
        :SetPriority("Arms",      "Str > 8% Hit > Crit > Expert > Mast > Haste")
        :SetPriority("Fury",      "Str > 8% Hit > Expert > Crit > 15% Hit > Mast > Haste")
        :SetPriority("Protect",   "Stam > Mast > Parry > Dodge > Hit")

else
    AddOn:AddStatPriority("DEATHKNIGHT-250", "BLOOD KNIGHT")
        :SetDefaultPriority("DeathBringer", "ilvl > Str > Haste 5% > Crit = Mast = Vers > Haste 5%+")
		:SetPriority("San'layn", "ilvl > Str > Haste > Crit = Mast = Vers")		
    AddOn:AddStatPriority("DEATHKNIGHT-251", "FROST KNIGHT")
        :SetDefaultPriority("Str > Crit > Haste > Mast > Vers")
        :SetPriority("PVP", "Str > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("DEATHKNIGHT-252", "UNHOLY KNIGHT")
        :SetDefaultPriority("Str > Haste > Mast > Crit > Vers")
        :SetPriority("PVP",   "Str > Vers > Mast = Haste > Crit")
		
	AddOn:AddStatPriority("DEMONHUNTER-577", "HAVOC")
        :SetPriority("Solo",  "Agil > Crit > Mast > Haste > Vers")
        :SetPriority("Multi", "Agil > Crit > Mast > Vers > Haste")
        :SetPriority("PVP", "Agil > Mast > Vers > Haste > Crit")
    AddOn:AddStatPriority("DEMONHUNTER-581", "MALICE")
        :SetDefaultPriority("Agil > Haste > Crit = Vers > Mast")

    AddOn:AddStatPriority("DRUID-102", "BOOMKIN")
        :SetDefaultPriority("Int > Mast > Vers > Haste > Crit")
        :SetPriority("PVP", "Int > Vers > Haste > Mast > Crit")
    AddOn:AddStatPriority("DRUID-103", "CAT DROOD")
        :SetPriority("Solo", "Mast = Crit > Agil > Haste > Vers")
        :SetPriority("Wildstalker", "Mast > Crit = Haste > Agil > Vers")
        :SetPriority("Druid of Claw", "Mast > Agil > Crit > Haste = Vers")		
        :SetPriority("PVP", "Agil > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("DRUID-104", "BEAR DROOD")
        :SetPriority("Survival", "ilvl > Armor = Agil = Stam > Haste > Vers > Mast > Crit")
        :SetPriority("Damage",   "Agil > Vers = Haste = Crit > Mast")
    AddOn:AddStatPriority("DRUID-105", "TREE DROOD")
        :SetPriority("Raid",    "Int > Haste > Mast > Crit = Vers")
        :SetPriority("Dungeon", "Int > Mast = Haste > Vers > Crit")
        :SetPriority("Damage", "Int > Haste > Vers > Crit > Mast")
        :SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")
		
	AddOn:AddStatPriority("EVOKER-1467", "DEVASTATION")
        :SetDefaultPriority("ilvl > Int > Crit > Vers = Mast = Haste")
		:SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("EVOKER-1468", "PRESERVATION")
        :SetPriority("Raid",    "Int > Mast > Crit > Haste > Vers")
        :SetPriority("Dungeon", "Int > Crit > Haste > Vers > Mast")
		:SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")
	AddOn:AddStatPriority("EVOKER-1473", "AUGMENTATION")
        :SetDefaultPriority("Chrono", "Int > Haste 10% > Mast = Crit > Haste 10%+ > Vers")
		:SetPriority("Scale Cmdr",    "Int > Haste 10% > Mast > Crit = Haste 10%+ > Vers")
		:SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")		

    AddOn:AddStatPriority("HUNTER-253", "BEAST TAMER")
        :SetPriority("Dark Ranger Solo", "Agil > Haste > Crit > Mast > Vers")
        :SetPriority("Pack Leader Multi", "Agil > Mast > Haste > Crit > Vers")
        :SetPriority("Pack Leader Solo", "Agil > Crit > Haste > Mast > Vers")
        :SetPriority("Pack Leader Multi", "Agil > Mast > Crit = Haste > Vers")
        :SetPriority("PVP", "Agil > Vers 20% > Haste 20% > Mast = Vers 20+ > Haste 20%+ > Crit")		
    AddOn:AddStatPriority("HUNTER-254", "SHARPSHOOTER")
        :SetDefaultPriority("Weapon DPS > Crit > Mast > Agil > Vers > Haste")
        :SetPriority("Dark Ranger Solo", "Weapon DPS > Crit > Haste > Mast > Agil > Vers")		
        :SetPriority("PVP", "Agil > Vers 20% > Haste 20% > Mast > Crit")
    AddOn:AddStatPriority("HUNTER-255", "SURVIVALIST")
        :SetPriority("Solo", "Mast > Agil > Haste = Crit = Vers")
        :SetPriority("Multi", "Mast > Agil > Haste = Crit > Vers")		
        :SetPriority("PVP", "Agil > Vers 20% > Haste 20% > Mast > Crit")

    AddOn:AddStatPriority("MAGE-62", "ARCANE")
        :SetDefaultPriority("Int > Mast = Haste > Vers > Crit")
        :SetPriority("PVP", "Int > Haste > Vers > Mast > Crit")
    AddOn:AddStatPriority("MAGE-63", "FIRE")
        :SetDefaultPriority("Int > Haste > Vers > Mast > Crit")
    AddOn:AddStatPriority("MAGE-64", "ICE")
        :SetDefaultPriority("Int > Mast > Haste > Crit 33% > Vers > Crit 33%+")
        :SetPriority("PVP", "Int > Haste > Vers > Mast > Crit")

    AddOn:AddStatPriority("MONK-268", "DRUNK MONK")
        :SetPriority("Defense", "ilvl = Agil = Armor > Vers = Mast = Crit > Haste")
        :SetPriority("Offense", "Agil > Vers = Crit > Haste > Mast")
    AddOn:AddStatPriority("MONK-269", "WINDWALKER")
        :SetDefaultPriority("Weapon Dam > Agi > Haste > Vers > Crit > Mast")
        :SetPriority("PVP", "Agil > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("MONK-270", "MISTWEAVER")
        :SetPriority("Raid",    "Int > Haste > Crit > Vers > Mast")
        :SetPriority("Dungeon", "Int > Haste > Mast > Vers > Crit")
        :SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")

    AddOn:AddStatPriority("PALADIN-65", "HEALADIN")
        :SetPriority("Raid",    "Int > Haste > Crit > Mast > Vers")
        :SetPriority("Dungeon", "Int > Haste > Crit > Vers > Mast")
        :SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("PALADIN-66", "TANKADIN")
        :SetDefaultPriority("Haste > Mast > Vers = Crit > Str = Stam")
    AddOn:AddStatPriority("PALADIN-70", "LOLADIN")
        :SetPriority("Crusader", "Mast > Str > Crit = Haste > Vers")
        :SetPriority("Templar", "Mast > Str > Crit > Haste > Vers")		
        :SetPriority("PVP", "Str > Vers > Mast > Haste = Crit")

    AddOn:AddStatPriority("PRIEST-256", "CLERIC")
        :SetDefaultPriority("Int > Haste > Mast > Crit > Vers")
        :SetPriority("PVP", "Int > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("PRIEST-257", "PRIEST")
        :SetPriority("Raid",  "Int > Mast = Crit > Vers > Haste")
        :SetPriority("Dungeon", "Int > Crit = Haste > Vers > Mast")
        :SetPriority("PVP",     "Int > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("PRIEST-258", "CULTIST")
        :SetDefaultPriority("Int > Haste > Mast > Crit = Vers")
        :SetPriority("PVP", "Int > Vers > Haste > Crit > Mast")

    AddOn:AddStatPriority("ROGUE-259", "ASSASSIN")
        :SetDefaultPriority("Agil > Mast > Crit > Haste > Vers")
        :SetPriority("PVP",     "Agil > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("ROGUE-260", "PIRATE")
        :SetPriority("Hidden Opp", "Agil > Vers > Haste 10% > Crit > Mast")
        :SetPriority("Keep Rollin", "Agil > Vers > Haste 20% > Crit > Mast")
		:SetPriority("PVP",     "Agil > Vers > Crit > Mast > Haste")
    AddOn:AddStatPriority("ROGUE-261", "THIEF")
        :SetDefaultPriority("Agil > Mast > Vers > Crit > Haste")
        :SetPriority("PVP",   "Agil > Vers > Mast > Crit > Haste")

    AddOn:AddStatPriority("SHAMAN-262", "TRUE SHAMAN")
	    :SetPriority("Fire",  "Int > Haste > Vers > Mast > Crit")
        :SetPriority("Lightning", "Int > Haste > Crit > Vers > Mast")
        :SetPriority("PVP", "Int > Vers > Haste > Mast > Crit")
    AddOn:AddStatPriority("SHAMAN-263", "PUNK SHAMAN")
        :SetPriority("Totemic", "Agil = Haste > Mast > Vers > Crit")
        :SetPriority("Storm", "Haste = Agil > Mast > Crit > Vers")		
        :SetPriority("PVP", "Agil > Vers > Mast > Haste > Crit")
    AddOn:AddStatPriority("SHAMAN-264", "HEAL SHAMAN")
        :SetPriority("Healer", "Int > ilvl > Vers = Crit > Haste = Mast")
        :SetPriority("Damage", "Int > ilvl > Haste > Vers = Crit = Mast")
        :SetPriority("Dungeon", "Int > ilvl > Vers > Crit = Mast = Haste")		
        :SetPriority("PVP",    "Int > Vers > Mast > Crit > Haste")

    AddOn:AddStatPriority("WARLOCK-265", "PLAGUEBRINGER")
        :SetDefaultPriority("Int > Mast = Crit > Haste > Vers")
        :SetPriority("PVP", "Int > Vers > Haste > Mast > Crit")
    AddOn:AddStatPriority("WARLOCK-266", "DEMONOLOGIST")
	    :SetPriority("Solo",  "Int > Haste 25% > Crit = Vers > Mast")
        :SetPriority("Multi", "Int > Haste 25% > Crit = Mast > Vers")
        :SetPriority("PVP", "Int > Vers > Haste > Mast > Crit")
    AddOn:AddStatPriority("WARLOCK-267", "DESTRUCTION")
		:SetDefaultPriority("Haste = Crit > Int > Mast > Vers")
        :SetPriority("PVP", "Int > Haste > Vers > Mast > Crit")

    AddOn:AddStatPriority("WARRIOR-71", "FIGHTER")
        :SetDefaultPriority("Str > Crit > Haste > Mast > Vers")
        :SetPriority("PVP", "Str > Vers > Haste = Mast > Crit")
    AddOn:AddStatPriority("WARRIOR-72", "BESERKER")
        :SetDefaultPriority("Str > Mast > Haste > Vers > Crit")
        :SetPriority("PVP", "Str > Vers > Haste > Mast > Crit")
    AddOn:AddStatPriority("WARRIOR-73", "CAVALIER")
        :SetDefaultPriority("ilvl > Haste > Vers = Crit > Mast > Armor > Str")
        :SetPriority("PVP",     "Str > Vers > Haste = Mast = Crit")		

end
